// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db_relationship_proj.Data;

#nullable disable

namespace db_relationship_proj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529064616_added many to many relationship")]
    partial class addedmanytomanyrelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("db_relationship_proj.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("db_relationship_proj.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("db_relationship_proj.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SerialNumberId")
                        .HasColumnType("int");

                    b.Property<int?>("SerialNumberId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SerialNumberId1");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "microphone",
                            Price = 245m,
                            SerialNumberId = 10
                        });
                });

            modelBuilder.Entity("db_relationship_proj.Models.ItemClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemClients");
                });

            modelBuilder.Entity("db_relationship_proj.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ItemId = 10,
                            Name = "mic10"
                        });
                });

            modelBuilder.Entity("db_relationship_proj.Models.Item", b =>
                {
                    b.HasOne("db_relationship_proj.Models.Category", "category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.HasOne("db_relationship_proj.Models.SerialNumber", "SerialNumber")
                        .WithMany()
                        .HasForeignKey("SerialNumberId1");

                    b.Navigation("SerialNumber");

                    b.Navigation("category");
                });

            modelBuilder.Entity("db_relationship_proj.Models.ItemClient", b =>
                {
                    b.HasOne("db_relationship_proj.Models.Client", "client")
                        .WithMany("itemClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db_relationship_proj.Models.Item", "item")
                        .WithMany("ItemClients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("item");
                });

            modelBuilder.Entity("db_relationship_proj.Models.SerialNumber", b =>
                {
                    b.HasOne("db_relationship_proj.Models.Item", "item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("item");
                });

            modelBuilder.Entity("db_relationship_proj.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("db_relationship_proj.Models.Client", b =>
                {
                    b.Navigation("itemClients");
                });

            modelBuilder.Entity("db_relationship_proj.Models.Item", b =>
                {
                    b.Navigation("ItemClients");
                });
#pragma warning restore 612, 618
        }
    }
}
